//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int id_bitacora { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_prosprecto { get; set; }
        public Nullable<int> id_reporte { get; set; }
        public Nullable<int> id_evento { get; set; }
        public Nullable<int> id_permiso { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public Nullable<int> id_sesion { get; set; }
        public Nullable<int> id_tipo_producto { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<int> id_usuario_afectado { get; set; }
    
        public virtual permiso permiso { get; set; }
        public virtual reporte reporte { get; set; }
        public virtual seguimiento seguimiento { get; set; }
        public virtual sesion sesion { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
        public virtual venta venta { get; set; }
        public virtual evento evento { get; set; }
        public virtual prospecto prospecto { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual producto producto { get; set; }
    }
}
