//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        public pregunta()
        {
            this.evaluacion_preguntas = new HashSet<evaluacion_preguntas>();
            this.plantillas = new HashSet<plantilla>();
        }
    
        public int id_pregunta { get; set; }
        public string pregunta1 { get; set; }
        public int peso { get; set; }
    
        public virtual ICollection<evaluacion_preguntas> evaluacion_preguntas { get; set; }
        public virtual ICollection<plantilla> plantillas { get; set; }
    }
}
