//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sesion
    {
        public sesion()
        {
            this.bitacoras = new HashSet<bitacora>();
        }
    
        public int id_sesion { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
