//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_kpi
    {
        public tipo_kpi()
        {
            this.kpis = new HashSet<kpi>();
        }
    
        public int id_tipo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<kpi> kpis { get; set; }
    }
}
