//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.bitacoras = new HashSet<bitacora>();
            this.bitacoras1 = new HashSet<bitacora>();
            this.historial_contrasennas = new HashSet<historial_contrasennas>();
            this.sesions = new HashSet<sesion>();
            this.ventas = new HashSet<venta>();
            this.prospectos = new HashSet<prospecto>();
            this.evaluaciones = new HashSet<evaluacione>();
            this.evaluaciones1 = new HashSet<evaluacione>();
            this.productos = new HashSet<producto>();
        }
    
        public int id_usuario { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string telefono { get; set; }
        public string password { get; set; }
        public bool activo { get; set; }
        public int id_rol { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
        public virtual ICollection<bitacora> bitacoras1 { get; set; }
        public virtual ICollection<historial_contrasennas> historial_contrasennas { get; set; }
        public virtual rol rol { get; set; }
        public virtual ICollection<sesion> sesions { get; set; }
        public virtual ICollection<venta> ventas { get; set; }
        public virtual ICollection<prospecto> prospectos { get; set; }
        public virtual ICollection<evaluacione> evaluaciones { get; set; }
        public virtual ICollection<evaluacione> evaluaciones1 { get; set; }
        public virtual ICollection<producto> productos { get; set; }
    }
}
