//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.bitacoras = new HashSet<bitacora>();
            this.productos = new HashSet<producto>();
        }
    
        public int id_venta { get; set; }
        public int id_usuario { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<producto> productos { get; set; }
    }
}
